
app:
  description: Welcome to ${app.name}
  greeting:
    list: One,Two,Three,Four,Five.Six,Seven
    messages: "{English:'Hello',Spanish:'Hola',French:'Bonjour',German:'Hallo'}"
  name: My Testing App

my:
  greeting: Hello Testing App from Git config repo in github.com
  list.greeting: One,Two,Three,Four,Five,Six,Seven
  map.greeting: "{English:'Hello',Spanish:'Hola',French:'Bonjour',German:'Hallo'}"

