app:
  description: "currency-exchange-service"
  
spring:
  datasource:
    url: "jdbc:mysql://host.docker.internal:3306/spring_microservices?useSSL=false"
    username: "root"
    password: "Puchki@0810"

  hibernate:
    dialect:
      storage_engine: "innodb"
      
  spring:
    jpa:
      database-platform: "org.hibernate.dialect.MySQL8Dialect"